# Generated by Django 4.1.5 on 2023-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('phone_model', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('memory', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
