# Generated by Django 4.1.5 on 2023-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
