# Generated by Django 4.1.5 on 2023-01-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_phone_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='title',
            new_name='brand',
        ),
    ]
