# Generated by Django 4.1.5 on 2023-01-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='phone',
            new_name='product',
        ),
    ]
